"""alter columns in plants

Revision ID: b5343aff2a4f
Revises: 80cd1764ed7e
Create Date: 2024-10-09 09:47:33.871725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5343aff2a4f'
down_revision = '80cd1764ed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
